<?php

declare(strict_types=1);

namespace App\Domains\SocialMedia\Models;

use App\Domains\ContentManagement\Posts\Models\Post;
use App\Domains\SocialMedia\Constants\PostStatus;
use App\Models\User;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;
use Illuminate\Database\Eloquent\Relations\HasMany;
use Illuminate\Database\Eloquent\Relations\HasOne;
use Illuminate\Database\Eloquent\SoftDeletes;
use Spatie\Activitylog\LogOptions;
use Spatie\Activitylog\Traits\LogsActivity;

class SocialPost extends Model
{
    use HasFactory, LogsActivity, SoftDeletes;

    protected $fillable = [
        'social_account_id',
        'user_id',
        'source_type',
        'source_blog_post_id',
        'content',
        'media_urls',
        'link_url',
        'status',
        'scheduled_at',
        'published_at',
        'platform_post_id',
        'platform_permalink',
        'error_message',
        'retry_count',
    ];

    protected $casts = [
        'media_urls' => 'array',
        'scheduled_at' => 'datetime',
        'published_at' => 'datetime',
        'retry_count' => 'integer',
    ];

    /**
     * Get the social account that owns this post.
     */
    public function socialAccount(): BelongsTo
    {
        return $this->belongsTo(SocialAccount::class);
    }

    /**
     * Get the user who created this post.
     */
    public function user(): BelongsTo
    {
        return $this->belongsTo(User::class);
    }

    /**
     * Get the source blog post (if auto-generated).
     */
    public function sourceBlogPost(): BelongsTo
    {
        return $this->belongsTo(Post::class, 'source_blog_post_id');
    }

    /**
     * Get all analytics for this post.
     */
    public function analytics(): HasMany
    {
        return $this->hasMany(SocialAnalytics::class);
    }

    /**
     * Get the latest analytics snapshot.
     */
    public function latestAnalytics(): HasOne
    {
        return $this->hasOne(SocialAnalytics::class)->latestOfMany('synced_at');
    }

    /**
     * Get all media attachments.
     */
    public function attachments(): HasMany
    {
        return $this->hasMany(SocialPostAttachment::class);
    }

    /**
     * Get the queue entry (if from auto-posting).
     */
    public function queueEntry(): HasOne
    {
        return $this->hasOne(BlogPostSocialQueue::class);
    }

    /**
     * Scope to filter by status.
     */
    public function scopeStatus($query, string $status)
    {
        return $query->where('status', $status);
    }

    /**
     * Scope to get draft posts.
     */
    public function scopeDraft($query)
    {
        return $query->where('status', PostStatus::DRAFT);
    }

    /**
     * Scope to get scheduled posts.
     */
    public function scopeScheduled($query)
    {
        return $query->where('status', PostStatus::SCHEDULED);
    }

    /**
     * Scope to get published posts.
     */
    public function scopePublished($query)
    {
        return $query->where('status', PostStatus::PUBLISHED);
    }

    /**
     * Scope to get failed posts.
     */
    public function scopeFailed($query)
    {
        return $query->where('status', PostStatus::FAILED);
    }

    /**
     * Scope to get posts due for publishing.
     */
    public function scopeDueForPublishing($query)
    {
        return $query->where('status', PostStatus::SCHEDULED)
            ->where('scheduled_at', '<=', now());
    }

    /**
     * Scope to filter by source type.
     */
    public function scopeSourceType($query, string $type)
    {
        return $query->where('source_type', $type);
    }

    /**
     * Scope to get manual posts.
     */
    public function scopeManual($query)
    {
        return $query->where('source_type', 'manual');
    }

    /**
     * Scope to get auto-generated posts.
     */
    public function scopeAutoGenerated($query)
    {
        return $query->where('source_type', 'auto_blog_post');
    }

    /**
     * Scope to filter by platform.
     */
    public function scopePlatform($query, string $platform)
    {
        return $query->whereHas('socialAccount', function ($q) use ($platform) {
            $q->where('platform', $platform);
        });
    }

    /**
     * Scope to get posts within date range.
     */
    public function scopeBetweenDates($query, $startDate, $endDate)
    {
        return $query->whereBetween('scheduled_at', [$startDate, $endDate]);
    }

    /**
     * Check if post is draft.
     */
    public function isDraft(): bool
    {
        return $this->status === PostStatus::DRAFT;
    }

    /**
     * Check if post is scheduled.
     */
    public function isScheduled(): bool
    {
        return $this->status === PostStatus::SCHEDULED;
    }

    /**
     * Check if post is published.
     */
    public function isPublished(): bool
    {
        return $this->status === PostStatus::PUBLISHED;
    }

    /**
     * Check if post failed.
     */
    public function isFailed(): bool
    {
        return $this->status === PostStatus::FAILED;
    }

    /**
     * Check if post can be retried.
     */
    public function canRetry(): bool
    {
        return $this->isFailed() && $this->retry_count < 3;
    }

    /**
     * Get status display name.
     */
    public function getStatusNameAttribute(): string
    {
        return PostStatus::getName($this->status);
    }

    /**
     * Get status color.
     */
    public function getStatusColorAttribute(): string
    {
        return PostStatus::getColor($this->status);
    }

    /**
     * Get platform name.
     */
    public function getPlatformNameAttribute(): string
    {
        return $this->socialAccount->platform_name ?? '';
    }

    /**
     * Get activity log options.
     */
    public function getActivitylogOptions(): LogOptions
    {
        return LogOptions::defaults()
            ->logOnly([
                'content',
                'status',
                'scheduled_at',
                'published_at',
            ])
            ->logOnlyDirty();
    }
}
